# Ensures the app can be embedded in Plato
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "ALLOWALL"
    Content-Security-Policy = "frame-ancestors https://clinic.platomedical.com https://*.platomedical.com 'self';"

# Functions directory (Netlify autodetects /netlify/functions)
[build]
  publish = "."

# Friendly redirects for functions
[[redirects]]
  from = "/api/env"
  to = "/.netlify/functions/env"
  status = 200
  force = true

[[redirects]]
  from = "/api/plato-create-note"
  to = "/.netlify/functions/plato-create-note"
  status = 200
  force = true
