[build]
  publish = "."
  command = ""

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = ""
    Content-Security-Policy = "frame-ancestors https://clinic.platomedical.com https://*.platomedical.com;"
    Referrer-Policy = "same-origin"
    X-Content-Type-Options = "nosniff"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"