[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "ALLOWALL"
    Content-Security-Policy = "frame-ancestors *"
    Referrer-Policy = "no-referrer-when-downgrade"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200